### ISSUE TITLE
Please give a simple example

### ISSUE THREAD

**Issue by olsonpm** [jsarenik/Mac-Ompose#1]
I cloned -> ran ./install.sh -> selected the karabiner option -> then tried composing a key and it didn't work.  Not sure what I'm missing but a simple example would confirm that I'm understanding the process correctly

**Comment by jsarenik** [comment]
Then you should at least log out and log in again.

**Comment by jsarenik** [comment]
Thanks for feed-back! Please let me know if logging-out helps.
