### ISSUE TITLE
Overwrites files

### ISSUE THREAD

**Issue by olsonpm** [jsarenik/Mac-Ompose#2]
Wish I would have checked this script before I ran it.  Didn't realize it overwrites both the DefaultKeyBinding.dict and private.xml files.  You really should back those up before copying over them

**Comment by jsarenik** [comment]
Sorry for late fix. Please have a look. It does not do multiple backups, but it checks if the files are the same. I do not have Mac anymore so please test and let me know if it's OK.

Thank you for reporting it! I really found it merely today and should check my GitHub notification emails...

**Comment by olsonpm** [comment]
Not a problem - I stopped such heavy usage of karabiner in favor of customizing hotkeys via bettertouchtool and osx's built in hotkey settings.  I appreciate you addressing the issue though.  I completely understand it's not easy finding time for side-projects :)

**Comment by jsarenik** [comment]
May I close this issue now (after merge, of course)? Thank you and good luck!

**Comment by olsonpm** [comment]
whoops - I should have closed it.  Thanks for checking.
