### ISSUE TITLE
Mappings using tilde (shift+`) do not work

### ISSUE THREAD

**Issue by LunarLanding** [jsarenik/Mac-Ompose#7]
Compose,  shift+ \` (which is ~), a  should give ã, but does not, it gives ~.
My workaround is mapping \` to F16 using Karabiner-Elements. In the dict, I replaced the unicode codes of \` and ~ with the codes for F16 and shift+F16, and then mapped F16 in the .dict back to \`, shift+F16 to ~.

**Comment by jsarenik** [comment]
@LunarLanding Thank you for this suggestion. I am actually not using MacOmpose for some time now and I thought it is already not working on the latest MacOS. What version of Mac OS (X) does it work for you on?

Thanks!

**Comment by LunarLanding** [comment]
@jsarenik I am on macOS Sierra, version 10.12.5 . I did not use the install.sh script, since I had already read on the steps it automates and I am using Karabiner-Elements, and not Karabiner, that does not work in this version of macOS.
I used this repo as an easy source for the perl script and Compose file.
The X11:Symbols module the script requires does not install easily: I had to find a blog post detailing alteration , and install from the modified source code. 
Then I copied the output .dict file to ~/Library/KeyBindings/ , applied the workaround discussed above, and it works. I have yet to try to use the Compose files that I use in Windows and Linux on OSX, for now they are similar enough.

**Comment by jsarenik** [comment]
The `X11::Symbols` package required to re-generate the `DefaultKeyBindings.dict` file can be installed like this (on a clean macOS Terminal):

```
# run sudo and enter password to get root shell
sudo -i
# install cpanminus
cpan App::cpanminus
# forcefully installs X11::Keysyms (i.e. do not run tests as we are on macOS)
cpanm X11::Keysyms --force
```

After that you can run `misc/update-KeyBinding.sh`

**Comment by LunarLanding** [comment]
I no longer use macOS.

**Comment by jsarenik** [comment]
> Compose, shift+ ` (which is ~), a should give ã, but does not, it gives ~.
> My workaround is mapping ` to F16 using Karabiner-Elements. In the dict, I replaced the unicode codes of ` and ~ with the codes for F16 and shift+F16, and then mapped F16 in the .dict back to `, shift+F16 to ~.

Thank you for this. I tested it now and what you write is still vital to make it work. Closing this issue. Hopefully someone finds it in the history if they need to write `ã`.
