### ISSUE TITLE
Karabiner is now Karabiner-Elements

### ISSUE THREAD

**Issue by alexnils** [jsarenik/Mac-Ompose#8]
Karabiner is now Karabiner-Elements and this has to be changed in your install.sh so that the path works, also the program itself looks a little bit different so you might want to update the description part related to assigning the keys.

**Comment by jsarenik** [comment]
@ajjetollah Thank you! I actually do not have or use MacOS anymore so I would not have any means to test it.

**Comment by jsarenik** [comment]
Fixed in e832a140dc8678648a8ba67e9b29bec38c3cc6cd
